language: java

install:
  - "./gradlew assemble"

script:
  - "./gradlew verify"
  
jdk:
  - oraclejdk8
  
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6

notifications:
  email: false
  slack:
    secure: "hGdY/i/T6RE4AbCjdLBp0Ig6rmr2y7VlKEDi+edzxlhmBnnVqyUFW1nE8qVV/SjfRLQCWZl3VhVMl5utOVpzbe0tCvcZLsYXJ4wx5aMo8J1Wm+XdgcF6Z6mYlZur35PlCv4gKa8zwjM2LhEXMeG/j8vzeZUh6uwQh165g6iivxB2fQNc0CvXNCOqNMR9dZOozVKvsmRY7XfOokLb8LdOdcAzM6IL3Rtq6Dbt1CFbIk/3SQhdynnG8pv7DbVTm3d+Xfmgz27c7EcmooVgpVTE7s9VE4dNn0cO0v2+nc7GO4Fz7CvOG03DChlZ/MD9nhBlwueICc1h80rSaAUX/VIauynoz9hWHAWE8I0MdZvrxms50O8tLKR1z6lc6ygPt086s4qo+8nZUqWjW+TXR0I/0FleAT92QnXSJ5+a1aDnfkm8c5IkIS2WbGbsXd0oWaPK6iQ3nD1qEergjJdbUg9Q71Uem197aNYSiT/roU0q0oQiIJk+M4YEMIgwWlN9yAhlPFwJm57QpSXzzoN3tyo86l/8ZcNijAg7K934zJ9IbOu0HWoRQSoVZdWS2QNWr3h3oLrHWhtnmVEMCCBzGvjo8Qg75b2RqnOcC8Dcp//mQmmtyys4xF8s4Bytk+wkUkI050wp8MNNv4gPPvwgtI8zTyYdNKFWEu6YcVfJiOT2soU="
